version: "3.7"

services:
  php:
    image: sf_fridge
    build:
      context: ./php
    ports:
      - ${APP_EXPOSED_PORT}:80
    volumes:
      - ./../:/var/www/html
      - ./php/config/vhosts:/etc/apache2/sites-enabled
      - ./php/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
    networks:
      - app-network
  postgres:
    image: postgres:15.1
    ports:
      - ${DATABASE_EXPOSED_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
